### ISSUE TITLE
AttributeError: 'OrderEnforcing' object has no attribute 'get_observables'

### ISSUE THREAD

**Issue by comparezz** [rparac/Prob-IRM#1]
Hi,  
I encountered an issue while trying to reproduce the results of the paper *Learning Robust Reward Machines from Noisy Labels*. Specifically, I encountered the following error when running the `dqrm_coffee_world.py` script:  

Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/czx/Desktop/copy/Prob-IRM-master/dqrm_coffee_world.py", line 99, in run
    env = _get_base_env(env_config["name"], run_config["seed"] + i, agent_id, label_factories,
  File "/home/czx/Desktop/copy/Prob-IRM-master/dqrm_coffee_world.py", line 31, in _get_base_env
    env = GymSubgoalAutomataAdapter(env, agent_id, render_mode=render_mode,  # type: ignore
  File "/home/czx/Desktop/copy/Prob-IRM-master/rm_marl/envs/gym_subgoal_automata_wrapper.py", line 36, in __init__
    self.observables = self.env.get_observables()  # self.env.get_restricted_observables()
AttributeError: 'OrderEnforcing' object has no attribute 'get_observables'

From the traceback, it seems that the issue stems from the `gym_subgoal_automata_wrapper.py` file, specifically the `get_observables` method.  
Steps to Reproduce  
1. Clone the repository and follow the setup instructions.  
2. Activate the conda environment and install all dependencies (`python=3.10.12`, `pip install -r requirements.txt`).  
3. Run `python dqrm_coffee_world.py`.  
 What I Tried  
- Verified that the dependencies in `requirements.txt` were correctly installed.  
- Attempted to debug the `gym_subgoal_automata_wrapper.py` file to adjust the logic.  
- Tested multiple versions of `gym`, including `0.21.0` and `0.26.0`.  
Unfortunately, these attempts did not resolve the issue.  
Request for Help  
I suspect the issue might be related to the `gym_subgoal_automata` library or an incompatibility with recent versions of `gym`. Could you kindly provide more details on the following:  
Are there any specific updates or debugging recommendations for resolving this issue?  
Any assistance would be greatly appreciated. Thank you!  

Environment Details  
- Python version: 3.10.12  
- Gym version: (Various, including 0.21.0 and 0.26.0)  
- OS: Ubuntu 22.04  
- ILASP version: 4.4.0  

Best regards,

**Comment by rparac** [comment]
Hi,

I am glad to hear that you are trying out my code :)
The bug was in requirements.txt. I forgot to update the dependency from gym to gymnasium.

This has been fixed on the main branch now. You can pull in the latest version and it should work (I tried it out with a fresh conda environment).

Please let me know if I can help you in any other way.

Kind regards,
Roko

**Comment by rparac** [comment]
Closing this as it seems to have been resolved
